[package]
name = "mdsgd"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "*"
ndarray-linalg = { version = "*", features = ["openblas-system"] }
openblas-src = "*"
petgraph = "*"
rand = "*"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false